#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore ..//OpenAPI/ && \
    dotnet build ..//OpenAPI/ && \
    echo "Now, run the following to start the project: dotnet run -p ..//OpenAPI/OpenAPI.csproj --launch-profile web"
