:: Generated by: https://openapi-generator.tech
::

@echo off

dotnet restore ../\OpenAPI
dotnet build ../\OpenAPI
echo Now, run the following to start the project: dotnet run -p ../\OpenAPI\OpenAPI.csproj --launch-profile web.
echo.
